### ISSUE TITLE
Create User defined function to do data cleaning

### ISSUE THREAD

**Issue by arnenator** [Tietgen-ITU/advanced-data-systems#5]
# What is it that we need to do here?
Since the textual data is not always as clean as it could be, we need to define a `user-defined function` to perform data cleaning. This will later be used to perform sentiment analysis over data that we haven't seen before but also to do it on data that we want to train with.

**Comment by arnenator** [comment]
Got it from @avborup 😝

**Comment by avborup** [comment]
Wow it's a beautiful function 🤩
